# Pipeline to run basic code quality tests as part of pull requests to the master branch.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

trigger: none
pr: none


variables:
- template: mnist-variables-template.yml
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_scoring'
  displayName: 'Model scoring'
  jobs:
  - job: "Training_Run_Report"
    displayName: "Determine if evaluation succeeded and new model is registered"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          python -m ml_service.pipelines.test_pipeline.py
      name: 'register_scoring_pipeline'
      displayName: "register scoring pipeline"
